
function(Configure_Test Target)
set_target_properties(${Target} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${Target}>")

if(WIN32)
set_target_properties( ${Target}
    PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${VKL_OUTPUT_DIR}/Debug
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${VKL_OUTPUT_DIR}/Release
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${VKL_OUTPUT_DIR}/RelWithDebInfo
    RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${VKL_OUTPUT_DIR}/MinSizeRel

    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${VKL_OUTPUT_DIR}/Debug
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${VKL_OUTPUT_DIR}/Release
    ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${VKL_OUTPUT_DIR}/RelWithDebInfo
    ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL ${VKL_OUTPUT_DIR}/MinSizeRel

    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${VKL_OUTPUT_DIR}/Debug
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${VKL_OUTPUT_DIR}/Release
    LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${VKL_OUTPUT_DIR}/RelWithDebInfo
    LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL ${VKL_OUTPUT_DIR}/MinSizeRel

    FOLDER "Tests"
)
else()
set_target_properties( ${Target}
    PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
    FOLDER "Tests"
)
endif()
endfunction()

function(Configure_Library Target)
if(WIN32)
set_target_properties( ${Target}
    PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${VKL_OUTPUT_DIR}/Debug
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${VKL_OUTPUT_DIR}/Release
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${VKL_OUTPUT_DIR}/RelWithDebInfo
    RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${VKL_OUTPUT_DIR}/MinSizeRel

    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${VKL_OUTPUT_DIR}/Debug
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${VKL_OUTPUT_DIR}/Release
    ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${VKL_OUTPUT_DIR}/RelWithDebInfo
    ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL ${VKL_OUTPUT_DIR}/MinSizeRel

    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${VKL_OUTPUT_DIR}/Debug
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${VKL_OUTPUT_DIR}/Release
    LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${VKL_OUTPUT_DIR}/RelWithDebInfo
    LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL ${VKL_OUTPUT_DIR}/MinSizeRel

    FOLDER "Libraries"
)
else()
set_target_properties( ${Target}
    PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
    FOLDER "Libraries"
)
endif()
endfunction()